### ISSUE TITLE
support mqtt

### ISSUE THREAD

**Issue by zfgjy2005** [ratcashdev/mitemp#1]
Thank you very much for your code.
Could you please update the code so that it can publish data to the mqtt broker and support more than one sensor?
Thank you.

**Comment by ratcashdev** [comment]
You can use this for as many sensors you wish, just need to add them each explicitly to the config.
as for MQTT: I have no such equipment/sw around to develop/test it. PRs are welcome.
OTOH i think there may be already existing solutions that take data from existing sensors and publish them.

**Comment by yolkhovyy** [comment]
Take a look at this pull request: https://github.com/ratcashdev/mitemp/pull/13

**Comment by ratcashdev** [comment]
#13 is closed with the agreement that it will be a new module. Therefore closing this issue as well.
