### ISSUE TITLE
Support to Mijia ClearGrass 

### ISSUE THREAD

**Issue by alexvenom** [ratcashdev/mitemp#11]
The new Mijia version with updated Electronic Paper screen would be nice:

https://cleargrass.com/cg_temp_rh_monitor/overview

The unit seems very familiar with the old LCD model but the regular xiaomi_miio won't read from it. 
Technology is BLE but the Services in the device are different and the binary array retrieved in _parse_data looks very different (looks encrypted).

**Comment by ratcashdev** [comment]
Don't have this device, sorry. PRs are welcome, however.

**Comment by ratcashdev** [comment]
Seems that it's already done: https://github.com/KalininAndreyVictorovich/mitemp_cgg1-home-assistant
