### ISSUE TITLE
Readings mismatch

### ISSUE THREAD

**Issue by yoyekyoyek** [ratcashdev/mitemp#12]
Hi, 
any idea why there's such a mismatch on readings depending on the backend used?

python3 demo.py --backend gatttool poll 58:2D:34:34:77:BD; python3 demo.py --backend bluepy poll 58:2D:34:34:77:BD
Getting data from Mi Temperature and Humidity Sensor
FW: 00.00.66
Name: MJ_HT_V1
Battery: 100
Temperature: 27.2
Humidity: 36.1

Getting data from Mi Temperature and Humidity Sensor
FW: 00.00.66
Name: MJ_HT_V1
Battery: 100
Temperature: 28.3
Humidity: 33.6

gatttool readings are the same as the device's screen, bluepy shows wrong data.

Thanks!

**Comment by ratcashdev** [comment]
Those measurement change several times a second. Unless you're sure that you made the two measurement at the exact same point in time, there's a high likelihood they'll be different.
