### ISSUE TITLE
Error with Xiaomi temp sensor v2 

### ISSUE THREAD

**Issue by acca84** [ratcashdev/mitemp#17]
Hello
I try to use your code to read the new xiaomi temp sensors
The command : demo.py --backend bluepy poll MAC   gives the result finishing by : 
...
self.battery = int(ord(res_battery))
TypeError: ord() expected a charcter, but string of length 15 found

How can i make it work with thoses sensors please ?

**Comment by maxic62** [comment]
+1

**Comment by jPPuetz** [comment]
Me and several others seem to have the same issue and reported it in home assistant repository. Take a look: https://github.com/home-assistant/home-assistant/issues/16456#issuecomment-578487934 for further information or log files.

**Comment by manichardtiger** [comment]
Hi
As there seems to be some confusion on the version of these sensors, I have the same problem but I get the  "TypeError: ord() expected a charcter, but string of length 15 found" at the self.firmware section. 
The sensor Im trying to use is the following which doesnt have battery indicators, probably why I get the string error at the self.firmare and not the self.battery:

![2020-01-27 15_18_51-Xiaomi Mijia Bluetooth Temperature Smart Humidity Sensor Digital Thermometer 2 o](https://user-images.githubusercontent.com/44494402/73177901-d3673b80-4118-11ea-8578-069ad92a78c6.png)

**Comment by jPPuetz** [comment]
> Hi
> As there seems to be some confusion on the version of these sensors, I have the same problem but I get the "TypeError: ord() expected a charcter, but string of length 15 found" at the self.firmware section.

I got the same device and the same errors:

```
2020-01-26 11:14:37 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.sleeping_room_temperature fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/mitemp_bt/sensor.py", line 156, in update
    data = self.poller.parameter_value(self.parameter)
  File "/usr/local/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 126, in parameter_value
    self.fill_cache()
  File "/usr/local/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 59, in fill_cache
    self.firmware_version()
  File "/usr/local/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 106, in firmware_version
    self.battery = int(ord(res_battery))
TypeError: ord() expected a character, but string of length 15 found
```

**Comment by svennd** [comment]
> ![2020-01-27 15_18_51-Xiaomi Mijia Bluetooth Temperature Smart Humidity Sensor Digital Thermometer 2 o](https://user-images.githubusercontent.com/44494402/73177901-d3673b80-4118-11ea-8578-069ad92a78c6.png)

I was able to use this script : https://github.com/JsBergbau/MiTemperature2 to get a readout; I tried to change this script but did not try that long;

**Comment by marklister** [comment]
Here's the debug log:

It's receiving this from the sensor: `Arguments: (24, b'miaomiaoce.com\x00')`

```
pi@raspberrypi:~/mitemp $ python3  demo.py --backend gatttool poll A4:C1:xx:xx:xx:xx  
WARNING: No module named 'pexpect'
Getting data from Mi Temperature and Humidity Sensor
DEBUG:btlewrap.gatttool:Enter read_ble (<_MainThread(MainThread, started 3069864160)>)
DEBUG:btlewrap.gatttool:Running gatttool with a timeout of 20: gatttool --device=A4:C1:xx:xx:xx:xx --addr-type=public --char-read -a 0x24 --adapter=hci0
DEBUG:btlewrap.gatttool:Finished gatttool
DEBUG:btlewrap.gatttool:Got "Characteristic value/descriptor: 54 69 6d 65 00" from gatttool
DEBUG:btlewrap.gatttool:Exit read_ble with result (<_MainThread(MainThread, started 3069864160)>)
DEBUG:mitemp_bt.mitemp_bt_poller:Received result for handle 36: b'Time\x00'
DEBUG:btlewrap.gatttool:Enter read_ble (<_MainThread(MainThread, started 3069864160)>)
DEBUG:btlewrap.gatttool:Running gatttool with a timeout of 20: gatttool --device=A4:C1:38:11:EB:7A --addr-type=public --char-read -a 0x18 --adapter=hci0
DEBUG:btlewrap.gatttool:Finished gatttool
DEBUG:btlewrap.gatttool:Got "Characteristic value/descriptor: 6d 69 61 6f 6d 69 61 6f 63 65 2e 63 6f 6d 00" from gatttool
DEBUG:btlewrap.gatttool:Exit read_ble with result (<_MainThread(MainThread, started 3069864160)>)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not bytes
Call stack:
  File "demo.py", line 97, in <module>
    main()
  File "demo.py", line 93, in main
    args.func(args)
  File "demo.py", line 27, in poll
    print("FW: {}".format(poller.firmware_version()))
  File "/home/pi/mitemp/mitemp_bt/mitemp_bt_poller.py", line 96, in firmware_version
    _HANDLE_READ_BATTERY_LEVEL, res_battery)
Message: 'Received result for handle %s: %d'
Arguments: (24, b'miaomiaoce.com\x00')
b'miaomiaoce.com\x00'
Traceback (most recent call last):
  File "demo.py", line 97, in <module>
    main()
  File "demo.py", line 93, in main
    args.func(args)
  File "demo.py", line 27, in poll
    print("FW: {}".format(poller.firmware_version()))
  File "/home/pi/mitemp/mitemp_bt/mitemp_bt_poller.py", line 107, in firmware_version
    self.battery = int(ord(res_battery))
TypeError: ord() expected a character, but string of length 15 found
pi@raspberrypi:~/mitemp $ 
```

**Comment by gallynero** [comment]
I create this #18 pull request for support the new thermometer, i not sure if the humedity is correct but read al params.

For test can use demo.py with --version V2 argument, for example:

python3 demo.py --backend gatttool --version V2 poll


Sorry if something is wrong, i don't touch python from long time.

**Comment by gallynero** [comment]
i fix the humidity value in the pull request #19, now is working ok.

If the autor not response i will adapt this to work with home assistant

**Comment by gallynero** [comment]
Hi,

i created a new integration for new themp sensor of xiaomi, can you download from https://github.com/gallynero/mitemp2_bt

**Comment by ratcashdev** [comment]
same as #18 Closing
