### ISSUE TITLE
Why clearing cache when Temp=0

### ISSUE THREAD

**Issue by javicalle** [ratcashdev/mitemp#3]
In the `_check_data` function there is the following validation:
```yaml
  if parsed[MI_TEMPERATURE] == 0:  # humidity over 100 procent
    self.clear_cache()
    return
```

Why is clearing cache when temp=0? This does not make sense to me. Maybe when humidity below 0, but not temperature.

I'm right?

**Comment by ratcashdev** [comment]
you're right, should be removed.
