### ISSUE TITLE
gatttool not found: [WinError 2]

### ISSUE THREAD

**Issue by MaxShavarsky** [ratcashdev/mitemp#6]
Trying to execute this code: 
from mitemp_bt.mitemp_bt_poller import MiTempBtPoller
from btlewrap.gatttool import GatttoolBackend

poller = MiTempBtPoller('my mac address', GatttoolBackend)

Output:
gatttool not found: [WinError 2]
I have already install pyblyez lib. 
Help pls!

**Comment by ratcashdev** [comment]
are you running this on WIN or Linux?
AFAIK, gattool is not available on Windows.
