### ISSUE TITLE
Could this be extended to work with the Xiaomi Body Scale?

### ISSUE THREAD

**Issue by andreimarinescu** [ratcashdev/mitemp#8]
Basically the title says it all. I've got a Xiaomi Scale that seems to work in a very similar fashion to the HT sensor. It emits BLE and it seems that the data is just encoded differently (I haven't dug very deep yet).

If so, would you accept a PR to this library for adding support for this device? I'm looking for a cleaner fashion to bring this data into Home Assistant, rather than the current implementations floating around that rely on an mqtt gateway.

Thanks!

**Comment by ratcashdev** [comment]
I'd say that should be a different lib. Feel free to clone this and adjust.
Apart from that, I don't own this device, sorry.
